In [33]:
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\admin\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: bleach in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.30 in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (0.1.30)
Requirement already satisfied: packaging in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (5.29.3)
Requirement already satisfied: python-dateutil in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (1.1.0)
Requirement already satisfied: python-slugify in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in c:\users\admin\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\users\admin\anaconda3\lib\site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\admin\anaconda3\lib\site-packages (from jupytext->kaggle) (0.5.0)
Requirement already satisfied: nbformat in c:\users\admin\anaconda3\lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in c:\users\admin\anaconda3\lib\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\admin\anaconda3\lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\admin\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\admin\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (4.25.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\admin\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\admin\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.28.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.5.0)
Requirement already satisfied: pywin32>=300 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (311)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\admin\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\anaconda3\lib\site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests->kaggle) (2025.11.12)
Requirement already satisfied: colorama in c:\users\admin\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)

In [34]:
!kaggle competitions download -c playground-series-s4e3

playground-series-s4e3.zip: Skipping, found more recently modified local copy (use --force to force download)

In [35]:
import zipfile

zip_path = "playground-series-s4e3.zip"
extract_path = "playground-series-s4e3"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

Dataset extracted successfully!

In [36]:
import pandas as pd
loc=extract_path + '/' + "train.csv"
df = pd.read_csv(loc)
df.head()

,id,X_Minimum,X_Maximum,Y_Minimum,Y_Maximum,Pixels_Areas,X_Perimeter,Y_Perimeter,Sum_of_Luminosity,Minimum_of_Luminosity,...,Orientation_Index,Luminosity_Index,SigmoidOfAreas,Pastry,Z_Scratch,K_Scatch,Stains,Dirtiness,Bumps,Other_Faults
0,0,584,590,909972,909977,16,8,5,2274,113,...,-0.5000,-0.0104,0.1417,0,0,0,1,0,0,0
1,1,808,816,728350,728372,433,20,54,44478,70,...,0.7419,-0.2997,0.9491,0,0,0,0,0,0,1
2,2,39,192,2212076,2212144,11388,705,420,1311391,29,...,-0.0105,-0.0944,1.0000,0,0,1,0,0,0,0
3,3,781,789,3353146,3353173,210,16,29,3202,114,...,0.6667,-0.0402,0.4025,0,0,1,0,0,0,0
4,4,1540,1560,618457,618502,521,72,67,48231,82,...,0.9158,-0.2455,0.9998,0,0,0,0,0,0,1

In [37]:
df.corr(method="pearson")

,id,X_Minimum,X_Maximum,Y_Minimum,Y_Maximum,Pixels_Areas,X_Perimeter,Y_Perimeter,Sum_of_Luminosity,Minimum_of_Luminosity,...,Orientation_Index,Luminosity_Index,SigmoidOfAreas,Pastry,Z_Scratch,K_Scatch,Stains,Dirtiness,Bumps,Other_Faults
id,1.000000,0.004657,0.004406,-0.007632,-0.006422,0.000662,0.003388,0.004432,0.006150,0.006247,...,0.009182,0.006124,-0.002821,0.006174,0.002916,-0.000357,0.004396,-0.003034,0.000462,-0.005091
X_Minimum,0.004657,1.000000,0.989767,0.016071,0.014247,-0.464759,-0.451961,-0.426514,-0.430073,0.337748,...,0.276871,-0.068844,-0.376973,0.119306,-0.107581,-0.510597,0.046159,0.044439,0.205123,0.169608
X_Maximum,0.004406,0.989767,1.000000,0.018909,0.016513,-0.391937,-0.378434,-0.356528,-0.363092,0.275571,...,0.237157,-0.079235,-0.319598,0.108808,-0.126807,-0.441177,0.036824,0.037949,0.186930,0.153448
Y_Minimum,-0.007632,0.016071,0.018909,1.000000,0.969552,-0.007370,-0.012712,-0.024876,-0.008189,-0.017321,...,-0.044202,-0.023000,-0.031511,-0.015512,-0.012143,0.010612,-0.039151,-0.005449,0.056442,-0.019227
Y_Maximum,-0.006422,0.014247,0.016513,0.969552,1.000000,-0.007019,-0.012377,-0.024798,-0.007809,-0.018739,...,-0.042490,-0.022869,-0.030345,-0.016287,-0.012899,0.011304,-0.040874,-0.007416,0.056610,-0.018533
Pixels_Areas,0.000662,-0.464759,-0.391937,-0.007370,-0.007019,1.000000,0.835079,0.834543,0.797843,-0.622867,...,-0.269013,-0.015081,0.542672,-0.101295,-0.081567,0.701014,-0.077470,-0.053548,-0.224037,-0.195931
X_Perimeter,0.003388,-0.451961,-0.378434,-0.012712,-0.012377,0.835079,1.000000,0.912579,0.802072,-0.603891,...,-0.234969,0.005212,0.561256,-0.104322,-0.070433,0.675056,-0.084615,-0.050186,-0.218289,-0.186234
Y_Perimeter,0.004432,-0.426514,-0.356528,-0.024876,-0.024798,0.834543,0.912579,1.000000,0.809171,-0.602826,...,-0.113968,-0.005650,0.608167,-0.064965,-0.062092,0.630270,-0.100204,-0.019334,-0.227256,-0.174581
Sum_of_Luminosity,0.006150,-0.430073,-0.363092,-0.008189,-0.007809,0.797843,0.802072,0.809171,1.000000,-0.580857,...,-0.234625,-0.013845,0.520282,-0.093160,-0.059598,0.640597,-0.074245,-0.046712,-0.207316,-0.184651
Minimum_of_Luminosity,0.006247,0.337748,0.275571,-0.017321,-0.018739,-0.622867,-0.603891,-0.602826,-0.580857,1.000000,...,0.179385,0.619174,-0.504692,-0.004622,0.061146,-0.586957,0.166976,0.077386,0.134339,0.208857
Maximum_of_Luminosity,-0.000925,-0.132955,-0.129669,-0.029160,-0.028312,0.130499,0.158036,0.160831,0.128569,0.397265,...,-0.113531,0.853856,0.018501,-0.086090,-0.076961,0.121755,0.115789,0.020471,-0.069808,-0.008368
Length_of_Conveyer,-0.001049,0.308740,0.293466,0.016586,0.015735,-0.208256,-0.206060,-0.188716,-0.194282,0.018612,...,0.180770,-0.210456,-0.260468,0.158670,-0.168217,-0.272611,-0.110403,-0.052626,0.183847,0.109370
TypeOfSteel_A300,0.000074,0.220151,0.189802,0.044781,0.044867,-0.304635,-0.300883,-0.304057,-0.282051,0.103835,...,0.065726,-0.215409,-0.346852,-0.007322,0.190070,-0.375064,-0.121983,-0.080021,0.245988,0.064727
TypeOfSteel_A400,-0.001497,-0.218122,-0.188033,-0.044328,-0.044422,0.300308,0.296467,0.299557,0.278000,-0.100916,...,-0.065357,0.214970,0.344353,0.007499,-0.189486,0.371701,0.121660,0.080314,-0.244734,-0.063922
Steel_Plate_Thickness,0.007583,0.188764,0.164789,-0.054389,-0.058683,-0.232467,-0.225757,-0.189628,-0.215082,0.133881,...,0.240923,-0.102066,-0.125354,0.080037,-0.010609,-0.303104,-0.079751,0.011784,0.008460,0.202910
Edges_Index,-0.009751,0.167358,0.129800,0.035762,0.034222,-0.337258,-0.326388,-0.320950,-0.309055,0.397904,...,0.080225,0.213547,-0.350934,-0.019327,-0.083015,-0.357833,0.143554,0.065458,0.192647,0.078373
Empty_Index,0.000389,-0.175624,-0.146167,-0.033792,-0.032824,0.269263,0.322417,0.338079,0.271448,-0.096133,...,-0.179199,0.085117,0.480116,-0.133623,0.085455,0.204526,-0.065599,-0.011674,-0.133638,0.005157
Square_Index,0.006813,0.045635,0.035124,0.033952,0.034552,0.024658,0.050052,0.003372,0.031948,0.062940,...,-0.209706,0.082997,-0.361511,-0.150458,0.005770,-0.050983,0.078036,-0.131689,0.175271,-0.007282
Outside_X_Index,-0.003570,-0.522112,-0.432545,0.019685,0.017271,0.764810,0.752470,0.700036,0.703912,-0.638549,...,-0.467688,-0.050740,0.609049,-0.139184,-0.087028,0.778859,-0.091404,-0.071064,-0.232276,-0.215491
Edges_X_Index,-0.007978,0.112746,0.095799,0.052710,0.051546,-0.303335,-0.378672,-0.469092,-0.315125,0.234592,...,-0.412696,0.072659,-0.538678,-0.101720,-0.052205,-0.156152,0.214387,-0.103736,0.160995,0.021238
Edges_Y_Index,-0.001631,0.460421,0.391743,-0.002647,-0.001382,-0.650704,-0.664781,-0.612157,-0.608297,0.467841,...,0.607271,-0.053778,-0.594737,0.201774,0.049456,-0.678464,0.088256,0.083560,0.206651,0.150978
Outside_Global_Index,0.010620,0.222109,0.190474,-0.025374,-0.023285,-0.205579,-0.174615,-0.081225,-0.177048,0.112480,...,0.863987,-0.115506,-0.105986,0.223768,0.056348,-0.322954,-0.155964,0.102842,0.049073,0.077869
LogOfAreas,-0.005981,-0.505024,-0.428875,-0.001754,-0.000995,0.774580,0.771546,0.790863,0.726483,-0.691406,...,-0.214866,-0.133567,0.872453,-0.068590,-0.050127,0.745533,-0.260941,-0.017160,-0.247261,-0.195268
Log_X_Index,-0.003837,-0.530728,-0.448348,0.015116,0.015624,0.749731,0.750418,0.705657,0.698035,-0.637711,...,-0.520981,-0.058458,0.748741,-0.177303,-0.058250,0.782110,-0.170906,-0.084384,-0.214500,-0.202018
Log_Y_Index,-0.005560,-0.375324,-0.316770,-0.023702,-0.022941,0.640033,0.667441,0.761117,0.615651,-0.585194,...,0.144861,-0.157437,0.852450,0.036549,-0.014947,0.546596,-0.293370,0.050548,-0.231861,-0.142845
Orientation_Index,0.009182,0.276871,0.237157,-0.044202,-0.042490,-0.269013,-0.234969,-0.113968,-0.234625,0.179385,...,1.000000,-0.104336,-0.089470,0.261302,0.069028,-0.414475,-0.119092,0.146887,0.034166,0.104130
Luminosity_Index,0.006124,-0.068844,-0.079235,-0.023000,-0.022869,-0.015081,0.005212,-0.005650,-0.013845,0.619174,...,-0.104336,1.000000,-0.119099,-0.103424,-0.048601,0.008687,0.167107,0.038891,-0.055822,0.037015
SigmoidOfAreas,-0.002821,-0.376973,-0.319598,-0.031511,-0.030345,0.542672,0.561256,0.608167,0.520282,-0.504692,...,-0.089470,-0.119099,1.000000,-0.042299,-0.001010,0.532203,-0.216223,0.018793,-0.221909,-0.129298
Pastry,0.006174,0.119306,0.108808,-0.015512,-0.016287,-0.101295,-0.104322,-0.064965,-0.093160,-0.004622,...,0.261302,-0.103424,-0.042299,1.000000,-0.072496,-0.133473,-0.050148,-0.046237,-0.164948,-0.206815
Z_Scratch,0.002916,-0.107581,-0.126807,-0.012143,-0.012899,-0.081567,-0.070433,-0.062092,-0.059598,0.061146,...,0.069028,-0.048601,-0.001010,-0.072496,1.000000,-0.117627,-0.044026,-0.040592,-0.144810,-0.181566
K_Scatch,-0.000357,-0.510597,-0.441177,0.010612,0.011304,0.701014,0.675056,0.630270,0.640597,-0.586957,...,-0.414475,0.008687,0.532203,-0.133473,-0.117627,1.000000,-0.081367,-0.075020,-0.267004,-0.330406
Stains,0.004396,0.046159,0.036824,-0.039151,-0.040874,-0.077470,-0.084615,-0.100204,-0.074245,0.166976,...,-0.119092,0.167107,-0.216223,-0.050148,-0.044026,-0.081367,1.000000,-0.028079,-0.100170,-0.125596
Dirtiness,-0.003034,0.044439,0.037949,-0.005449,-0.007416,-0.053548,-0.050186,-0.019334,-0.046712,0.077386,...,0.146887,0.038891,0.018793,-0.046237,-0.040592,-0.075020,-0.028079,1.000000,-0.092357,-0.115800
Bumps,0.000462,0.205123,0.186930,0.056442,0.056610,-0.224037,-0.218289,-0.227256,-0.207316,0.134339,...,0.034166,-0.055822,-0.221909,-0.164948,-0.144810,-0.267004,-0.100170,-0.092357,1.000000,-0.413112
Other_Faults,-0.005091,0.169608,0.153448,-0.019227,-0.018533,-0.195931,-0.186234,-0.174581,-0.184651,0.208857,...,0.104130,0.037015,-0.129298,-0.206815,-0.181566,-0.330406,-0.125596,-0.115800,-0.413112,1.000000

In [38]:
df.corr(method="pearson")["Minimum_of_Luminosity"]

id                       0.006247
X_Minimum                0.337748
X_Maximum                0.275571
Y_Minimum               -0.017321
Y_Maximum               -0.018739
Pixels_Areas            -0.622867
X_Perimeter             -0.603891
Y_Perimeter             -0.602826
Sum_of_Luminosity       -0.580857
Minimum_of_Luminosity    1.000000
Maximum_of_Luminosity    0.397265
Length_of_Conveyer       0.018612
TypeOfSteel_A300         0.103835
TypeOfSteel_A400        -0.100916
Steel_Plate_Thickness    0.133881
Edges_Index              0.397904
Empty_Index             -0.096133
Square_Index             0.062940
Outside_X_Index         -0.638549
Edges_X_Index            0.234592
Edges_Y_Index            0.467841
Outside_Global_Index     0.112480
LogOfAreas              -0.691406
Log_X_Index             -0.637711
Log_Y_Index             -0.585194
Orientation_Index        0.179385
Luminosity_Index         0.619174
SigmoidOfAreas          -0.504692
Pastry                  -0.004622
Z_Scratch                0.061146
K_Scatch                -0.586957
Stains                   0.166976
Dirtiness                0.077386
Bumps                    0.134339
Other_Faults             0.208857
Name: Minimum_of_Luminosity, dtype: float64

In [39]:
# correlation between "Dirtiness" vs all
df.corr(method="pearson")["Dirtiness"]

id                      -0.003034
X_Minimum                0.044439
X_Maximum                0.037949
Y_Minimum               -0.005449
Y_Maximum               -0.007416
Pixels_Areas            -0.053548
X_Perimeter             -0.050186
Y_Perimeter             -0.019334
Sum_of_Luminosity       -0.046712
Minimum_of_Luminosity    0.077386
Maximum_of_Luminosity    0.020471
Length_of_Conveyer      -0.052626
TypeOfSteel_A300        -0.080021
TypeOfSteel_A400         0.080314
Steel_Plate_Thickness    0.011784
Edges_Index              0.065458
Empty_Index             -0.011674
Square_Index            -0.131689
Outside_X_Index         -0.071064
Edges_X_Index           -0.103736
Edges_Y_Index            0.083560
Outside_Global_Index     0.102842
LogOfAreas              -0.017160
Log_X_Index             -0.084384
Log_Y_Index              0.050548
Orientation_Index        0.146887
Luminosity_Index         0.038891
SigmoidOfAreas           0.018793
Pastry                  -0.046237
Z_Scratch               -0.040592
K_Scatch                -0.075020
Stains                  -0.028079
Dirtiness                1.000000
Bumps                   -0.092357
Other_Faults            -0.115800
Name: Dirtiness, dtype: float64

In [40]:
# pearson correlation coefficient between "Dirtiness" vs "Minimum_of_Luminosity"
df.corr(method="pearson")["Dirtiness"]["Minimum_of_Luminosity"]

np.float64(0.07738595131081434)

In [41]:
df.corr(method="kendall")

,id,X_Minimum,X_Maximum,Y_Minimum,Y_Maximum,Pixels_Areas,X_Perimeter,Y_Perimeter,Sum_of_Luminosity,Minimum_of_Luminosity,...,Orientation_Index,Luminosity_Index,SigmoidOfAreas,Pastry,Z_Scratch,K_Scatch,Stains,Dirtiness,Bumps,Other_Faults
id,1.000000,0.003924,0.002812,-0.003447,-0.003592,-0.002240,0.000133,-0.002825,-0.002487,0.004323,...,0.005733,0.003914,-0.001109,0.005041,0.002381,-0.000291,0.003589,-0.002477,0.000377,-0.004157
X_Minimum,0.003924,1.000000,0.924833,-0.024763,-0.025373,-0.243739,-0.247131,-0.234457,-0.251252,0.157608,...,0.168649,-0.026529,-0.238809,0.088110,-0.080163,-0.389323,0.031717,0.035455,0.157855,0.129794
X_Maximum,0.002812,0.924833,1.000000,-0.014120,-0.014954,-0.191215,-0.194463,-0.187000,-0.200016,0.116225,...,0.139708,-0.039853,-0.194078,0.080473,-0.111625,-0.326660,0.027775,0.032116,0.144408,0.115842
Y_Minimum,-0.003447,-0.024763,-0.014120,1.000000,0.972268,0.018761,0.019047,0.015326,0.018358,-0.060165,...,-0.060127,-0.029361,0.016796,-0.020891,-0.017377,0.085746,-0.037083,-0.002469,0.026625,-0.046450
Y_Maximum,-0.003592,-0.025373,-0.014954,0.972268,1.000000,0.019407,0.018973,0.015588,0.018953,-0.060449,...,-0.059020,-0.027668,0.017683,-0.021724,-0.017836,0.086633,-0.038152,-0.004586,0.027417,-0.046059
Pixels_Areas,-0.002240,-0.243739,-0.191215,0.018761,0.019407,1.000000,0.722522,0.795448,0.891717,-0.370760,...,0.013689,-0.108216,0.843472,-0.018875,-0.011121,0.475844,-0.225583,0.009749,-0.178558,-0.118381
X_Perimeter,0.000133,-0.247131,-0.194463,0.019047,0.018973,0.722522,1.000000,0.713930,0.711883,-0.303760,...,-0.112644,-0.043821,0.759240,-0.080897,0.006047,0.478720,-0.204700,-0.005967,-0.176874,-0.105483
Y_Perimeter,-0.002825,-0.234457,-0.187000,0.015326,0.015588,0.795448,0.713930,1.000000,0.767379,-0.346929,...,0.091661,-0.090230,0.806596,0.009652,-0.006333,0.463070,-0.224298,0.030821,-0.205939,-0.111732
Sum_of_Luminosity,-0.002487,-0.251252,-0.200016,0.018358,0.018953,0.891717,0.711883,0.767379,1.000000,-0.319777,...,-0.005045,-0.058292,0.813499,-0.028845,-0.015895,0.473849,-0.217145,0.011774,-0.177750,-0.116399
Minimum_of_Luminosity,0.004323,0.157608,0.116225,-0.060165,-0.060449,-0.370760,-0.303760,-0.346929,-0.319777,1.000000,...,0.060551,0.577176,-0.334227,-0.030797,0.042229,-0.411366,0.170452,0.071760,0.073131,0.155279
Maximum_of_Luminosity,0.000948,-0.083335,-0.082598,-0.035027,-0.032905,0.007511,0.059420,0.018655,0.053452,0.361328,...,-0.066938,0.669309,0.014609,-0.071097,-0.068791,0.067160,0.140170,0.033481,-0.055756,0.002240
Length_of_Conveyer,0.000434,0.170063,0.165752,-0.007136,-0.006312,-0.103253,-0.128169,-0.108297,-0.113268,-0.043955,...,0.113036,-0.065446,-0.122775,0.115923,-0.218331,-0.146190,-0.093559,-0.031025,0.133791,0.086673
TypeOfSteel_A300,0.000060,0.165064,0.133586,0.027305,0.026854,-0.290103,-0.263670,-0.304900,-0.306441,0.018631,...,0.042577,-0.169142,-0.288642,-0.007322,0.190070,-0.375064,-0.121983,-0.080021,0.245988,0.064727
TypeOfSteel_A400,-0.001222,-0.163577,-0.132346,-0.027342,-0.026905,0.287833,0.261436,0.302631,0.304249,-0.016597,...,-0.042258,0.168532,0.286463,0.007499,-0.189486,0.371701,0.121660,0.080314,-0.244734,-0.063922
Steel_Plate_Thickness,0.005458,0.198606,0.166671,-0.063629,-0.067635,-0.213836,-0.227509,-0.201389,-0.224541,0.101842,...,0.214665,-0.096289,-0.214883,0.093732,0.068367,-0.437590,-0.039671,0.030172,0.110642,0.158425
Edges_Index,-0.004671,0.115956,0.070720,-0.011118,-0.011901,-0.266550,-0.250657,-0.272959,-0.247565,0.260352,...,0.026698,0.149482,-0.258024,-0.024751,-0.059001,-0.292391,0.111734,0.042482,0.167150,0.061342
Empty_Index,-0.000508,-0.110412,-0.097807,-0.014638,-0.013376,0.292895,0.395798,0.311949,0.299212,-0.030536,...,-0.109071,0.103199,0.336702,-0.115593,0.072435,0.189713,-0.050784,-0.010540,-0.120171,-0.001530
Square_Index,0.004378,0.025774,0.016620,0.022796,0.023097,-0.222095,-0.202650,-0.294929,-0.217404,0.031563,...,-0.241093,0.066811,-0.239014,-0.126809,0.004518,-0.040337,0.063079,-0.106451,0.143814,-0.005676
Outside_X_Index,-0.002695,-0.268573,-0.197805,0.038228,0.038358,0.567587,0.694302,0.512308,0.568748,-0.255210,...,-0.312973,-0.024957,0.614283,-0.167618,0.011595,0.488757,-0.173321,-0.057866,-0.122690,-0.111048
Edges_X_Index,-0.006451,0.062328,0.054224,0.026524,0.026272,-0.383768,-0.405862,-0.446456,-0.370594,0.133815,...,-0.288258,0.020053,-0.382421,-0.082888,-0.045878,-0.122752,0.173471,-0.078744,0.130571,0.014202
Edges_Y_Index,-0.001071,0.269887,0.221425,-0.031287,-0.031262,-0.448457,-0.585751,-0.436821,-0.459333,0.186472,...,0.386738,-0.068424,-0.481604,0.201505,0.001402,-0.512599,0.091761,0.066797,0.171623,0.087957
Outside_Global_Index,0.008576,0.159699,0.132006,-0.043804,-0.042734,-0.032655,-0.173058,0.022485,-0.051871,0.025990,...,0.720677,-0.090672,-0.070276,0.220907,0.055557,-0.314644,-0.155069,0.101897,0.045773,0.076220
LogOfAreas,-0.002335,-0.243915,-0.190905,0.018727,0.019433,0.991298,0.723315,0.796220,0.892223,-0.371028,...,0.013683,-0.107980,0.844054,-0.019018,-0.011311,0.476113,-0.225729,0.009430,-0.178409,-0.118254
Log_X_Index,-0.002014,-0.257887,-0.185016,0.038072,0.038392,0.574860,0.702172,0.514436,0.572635,-0.280754,...,-0.323782,-0.042326,0.619763,-0.162345,-0.001821,0.490605,-0.186519,-0.067787,-0.112625,-0.109657
Log_Y_Index,-0.004135,-0.211915,-0.170699,0.011852,0.012619,0.745999,0.619808,0.876494,0.712834,-0.357508,...,0.182964,-0.115543,0.740328,0.041863,-0.006303,0.425648,-0.224069,0.047206,-0.200167,-0.108786
Orientation_Index,0.005733,0.168649,0.139708,-0.060127,-0.059020,0.013689,-0.112644,0.091661,-0.005045,0.060551,...,1.000000,-0.063346,-0.017448,0.219913,0.055203,-0.331818,-0.102733,0.125674,0.017548,0.085120
Luminosity_Index,0.003914,-0.026529,-0.039853,-0.029361,-0.027668,-0.108216,-0.043821,-0.090230,-0.058292,0.577176,...,-0.063346,1.000000,-0.098678,-0.086949,-0.030451,-0.042952,0.175062,0.051613,-0.039822,0.044262
SigmoidOfAreas,-0.001109,-0.238809,-0.194078,0.016796,0.017683,0.843472,0.759240,0.806596,0.813499,-0.334227,...,-0.017448,-0.098678,1.000000,-0.033503,0.000366,0.469350,-0.226351,0.008422,-0.183088,-0.110221
Pastry,0.005041,0.088110,0.080473,-0.020891,-0.021724,-0.018875,-0.080897,0.009652,-0.028845,-0.030797,...,0.219913,-0.086949,-0.033503,1.000000,-0.072496,-0.133473,-0.050148,-0.046237,-0.164948,-0.206815
Z_Scratch,0.002381,-0.080163,-0.111625,-0.017377,-0.017836,-0.011121,0.006047,-0.006333,-0.015895,0.042229,...,0.055203,-0.030451,0.000366,-0.072496,1.000000,-0.117627,-0.044026,-0.040592,-0.144810,-0.181566
K_Scatch,-0.000291,-0.389323,-0.326660,0.085746,0.086633,0.475844,0.478720,0.463070,0.473849,-0.411366,...,-0.331818,-0.042952,0.469350,-0.133473,-0.117627,1.000000,-0.081367,-0.075020,-0.267004,-0.330406
Stains,0.003589,0.031717,0.027775,-0.037083,-0.038152,-0.225583,-0.204700,-0.224298,-0.217145,0.170452,...,-0.102733,0.175062,-0.226351,-0.050148,-0.044026,-0.081367,1.000000,-0.028079,-0.100170,-0.125596
Dirtiness,-0.002477,0.035455,0.032116,-0.002469,-0.004586,0.009749,-0.005967,0.030821,0.011774,0.071760,...,0.125674,0.051613,0.008422,-0.046237,-0.040592,-0.075020,-0.028079,1.000000,-0.092357,-0.115800
Bumps,0.000377,0.157855,0.144408,0.026625,0.027417,-0.178558,-0.176874,-0.205939,-0.177750,0.073131,...,0.017548,-0.039822,-0.183088,-0.164948,-0.144810,-0.267004,-0.100170,-0.092357,1.000000,-0.413112
Other_Faults,-0.004157,0.129794,0.115842,-0.046450,-0.046059,-0.118381,-0.105483,-0.111732,-0.116399,0.155279,...,0.085120,0.044262,-0.110221,-0.206815,-0.181566,-0.330406,-0.125596,-0.115800,-0.413112,1.000000

In [42]:
df.corr(method="spearman")

,id,X_Minimum,X_Maximum,Y_Minimum,Y_Maximum,Pixels_Areas,X_Perimeter,Y_Perimeter,Sum_of_Luminosity,Minimum_of_Luminosity,...,Orientation_Index,Luminosity_Index,SigmoidOfAreas,Pastry,Z_Scratch,K_Scatch,Stains,Dirtiness,Bumps,Other_Faults
id,1.000000,0.005851,0.004216,-0.005187,-0.005400,-0.003422,0.000166,-0.004197,-0.003803,0.006450,...,0.008505,0.005879,-0.001673,0.006174,0.002916,-0.000357,0.004396,-0.003034,0.000462,-0.005091
X_Minimum,0.005851,1.000000,0.977841,-0.035452,-0.036452,-0.366647,-0.361854,-0.354966,-0.374050,0.251523,...,0.243797,-0.047840,-0.356108,0.107174,-0.097507,-0.473560,0.038580,0.043126,0.192010,0.157877
X_Maximum,0.004216,0.977841,1.000000,-0.021023,-0.022307,-0.306354,-0.303813,-0.296533,-0.315465,0.189645,...,0.203731,-0.064414,-0.300172,0.098404,-0.136498,-0.399447,0.033964,0.039273,0.176585,0.141654
Y_Minimum,-0.005187,-0.035452,-0.021023,1.000000,0.973760,0.030062,0.030074,0.023788,0.028973,-0.094029,...,-0.090416,-0.044863,0.023431,-0.025576,-0.021275,0.104977,-0.045400,-0.003023,0.032597,-0.056868
Y_Maximum,-0.005400,-0.036452,-0.022307,0.973760,1.000000,0.031042,0.029966,0.024262,0.029831,-0.094535,...,-0.088831,-0.042159,0.024758,-0.026596,-0.021837,0.106064,-0.046709,-0.005614,0.033566,-0.056389
Pixels_Areas,-0.003422,-0.366647,-0.306354,0.030062,0.031042,1.000000,0.878027,0.935105,0.966650,-0.516381,...,-0.035146,-0.166926,0.961479,-0.023074,-0.013595,0.581717,-0.275774,0.011918,-0.218287,-0.144720
X_Perimeter,0.000166,-0.361854,-0.303813,0.030074,0.029966,0.878027,1.000000,0.864567,0.871331,-0.430484,...,-0.203967,-0.069192,0.907369,-0.098227,0.007342,0.581273,-0.248551,-0.007245,-0.214765,-0.128079
Y_Perimeter,-0.004197,-0.354966,-0.296533,0.023788,0.024262,0.935105,0.864567,1.000000,0.914678,-0.484224,...,0.056823,-0.139215,0.940953,0.011720,-0.007690,0.562279,-0.272352,0.037424,-0.250060,-0.135670
Sum_of_Luminosity,-0.003803,-0.374050,-0.315465,0.028973,0.029831,0.966650,0.871331,0.914678,1.000000,-0.453140,...,-0.058584,-0.090816,0.941448,-0.035315,-0.019461,0.580137,-0.265852,0.014415,-0.217621,-0.142508
Minimum_of_Luminosity,0.006450,0.251523,0.189645,-0.094029,-0.094535,-0.516381,-0.430484,-0.484224,-0.453140,1.000000,...,0.097630,0.725796,-0.473158,-0.037452,0.051355,-0.500267,0.207289,0.087268,0.088935,0.188837
Maximum_of_Luminosity,0.001459,-0.120304,-0.120470,-0.052073,-0.048923,0.009371,0.083976,0.024281,0.076100,0.461646,...,-0.099532,0.831969,0.017637,-0.084450,-0.081712,0.079774,0.166497,0.039770,-0.066228,0.002661
Length_of_Conveyer,0.000663,0.239199,0.233552,-0.011397,-0.010210,-0.151272,-0.185404,-0.158871,-0.165029,-0.063819,...,0.157161,-0.094340,-0.175757,0.137869,-0.259665,-0.173866,-0.111271,-0.036899,0.159120,0.103082
TypeOfSteel_A300,0.000074,0.200778,0.163351,0.033428,0.032877,-0.354650,-0.320153,-0.370223,-0.375178,0.022657,...,0.052007,-0.207034,-0.346259,-0.007322,0.190070,-0.375064,-0.121983,-0.080021,0.245988,0.064727
TypeOfSteel_A400,-0.001497,-0.198969,-0.161836,-0.033474,-0.032939,0.351875,0.317441,0.367467,0.372494,-0.020183,...,-0.051618,0.206287,0.343644,0.007499,-0.189486,0.371701,0.121660,0.080314,-0.244734,-0.063922
Steel_Plate_Thickness,0.007544,0.270247,0.229162,-0.087321,-0.092878,-0.316529,-0.329554,-0.297507,-0.331664,0.144094,...,0.286793,-0.135624,-0.310871,0.105499,0.076950,-0.492524,-0.044651,0.033960,0.124531,0.178313
Edges_Index,-0.006998,0.188598,0.162321,-0.017391,-0.018542,-0.380393,-0.349715,-0.391287,-0.351778,0.384216,...,0.037413,0.224463,-0.367934,-0.030239,-0.072084,-0.357222,0.136509,0.051902,0.204212,0.074943
Empty_Index,-0.000722,-0.169564,-0.148670,-0.020604,-0.018718,0.431829,0.576210,0.451246,0.442222,-0.031529,...,-0.178789,0.153152,0.491838,-0.141418,0.088617,0.232097,-0.062130,-0.012895,-0.147019,-0.001872
Square_Index,0.006610,0.037779,0.023955,0.034104,0.034548,-0.320395,-0.291225,-0.402687,-0.314475,0.047726,...,-0.286826,0.101091,-0.342844,-0.154673,0.005510,-0.049201,0.076939,-0.129841,0.175415,-0.006923
Outside_X_Index,-0.004083,-0.381933,-0.322166,0.056360,0.056477,0.748366,0.865605,0.689853,0.752156,-0.379493,...,-0.459468,-0.034038,0.790583,-0.203699,0.014091,0.593966,-0.210630,-0.070322,-0.149100,-0.134951
Edges_X_Index,-0.009624,0.093669,0.082391,0.038778,0.038417,-0.539413,-0.562350,-0.608528,-0.523938,0.194537,...,-0.415560,0.032109,-0.530157,-0.101052,-0.055932,-0.149653,0.211485,-0.096000,0.159185,0.017314
Edges_Y_Index,-0.001492,0.366505,0.312762,-0.045048,-0.045003,-0.591935,-0.744943,-0.572989,-0.606710,0.269033,...,0.536507,-0.095830,-0.633451,0.230914,0.001606,-0.587410,0.105154,0.076546,0.196671,0.100794
Outside_Global_Index,0.010664,0.195881,0.162286,-0.054545,-0.053214,-0.045775,-0.217285,0.021236,-0.069309,0.032655,...,0.866499,-0.113161,-0.091037,0.224501,0.056461,-0.319762,-0.157592,0.103555,0.046517,0.077460
LogOfAreas,-0.003559,-0.366440,-0.305989,0.029868,0.030887,0.998439,0.878386,0.935574,0.967505,-0.516690,...,-0.035703,-0.166690,0.961960,-0.023249,-0.013827,0.582049,-0.275955,0.011529,-0.218105,-0.144566
Log_X_Index,-0.003020,-0.365842,-0.304825,0.055877,0.056317,0.746694,0.863140,0.683453,0.747540,-0.404891,...,-0.466752,-0.060287,0.787979,-0.195151,-0.002189,0.589746,-0.224211,-0.081485,-0.135384,-0.131816
Log_Y_Index,-0.006129,-0.325582,-0.271017,0.019041,0.020169,0.905140,0.792897,0.962017,0.877563,-0.497474,...,0.190924,-0.176982,0.898419,0.050746,-0.007641,0.515966,-0.271614,0.057223,-0.242640,-0.131869
Orientation_Index,0.008505,0.243797,0.203731,-0.090416,-0.088831,-0.035146,-0.203967,0.056823,-0.058584,0.097630,...,1.000000,-0.092287,-0.069147,0.268623,0.067430,-0.405315,-0.125488,0.153510,0.021435,0.103974
Luminosity_Index,0.005879,-0.047840,-0.064414,-0.044863,-0.042159,-0.166926,-0.069192,-0.139215,-0.090816,0.725796,...,-0.092287,1.000000,-0.146860,-0.106428,-0.037273,-0.052574,0.214281,0.063176,-0.048743,0.054178
SigmoidOfAreas,-0.001673,-0.356108,-0.300172,0.023431,0.024758,0.961479,0.907369,0.940953,0.941448,-0.473158,...,-0.069147,-0.146860,1.000000,-0.040191,0.000439,0.563038,-0.271534,0.010103,-0.219634,-0.132223
Pastry,0.006174,0.107174,0.098404,-0.025576,-0.026596,-0.023074,-0.098227,0.011720,-0.035315,-0.037452,...,0.268623,-0.106428,-0.040191,1.000000,-0.072496,-0.133473,-0.050148,-0.046237,-0.164948,-0.206815
Z_Scratch,0.002916,-0.097507,-0.136498,-0.021275,-0.021837,-0.013595,0.007342,-0.007690,-0.019461,0.051355,...,0.067430,-0.037273,0.000439,-0.072496,1.000000,-0.117627,-0.044026,-0.040592,-0.144810,-0.181566
K_Scatch,-0.000357,-0.473560,-0.399447,0.104977,0.106064,0.581717,0.581273,0.562279,0.580137,-0.500267,...,-0.405315,-0.052574,0.563038,-0.133473,-0.117627,1.000000,-0.081367,-0.075020,-0.267004,-0.330406
Stains,0.004396,0.038580,0.033964,-0.045400,-0.046709,-0.275774,-0.248551,-0.272352,-0.265852,0.207289,...,-0.125488,0.214281,-0.271534,-0.050148,-0.044026,-0.081367,1.000000,-0.028079,-0.100170,-0.125596
Dirtiness,-0.003034,0.043126,0.039273,-0.003023,-0.005614,0.011918,-0.007245,0.037424,0.014415,0.087268,...,0.153510,0.063176,0.010103,-0.046237,-0.040592,-0.075020,-0.028079,1.000000,-0.092357,-0.115800
Bumps,0.000462,0.192010,0.176585,0.032597,0.033566,-0.218287,-0.214765,-0.250060,-0.217621,0.088935,...,0.021435,-0.048743,-0.219634,-0.164948,-0.144810,-0.267004,-0.100170,-0.092357,1.000000,-0.413112
Other_Faults,-0.005091,0.157877,0.141654,-0.056868,-0.056389,-0.144720,-0.128079,-0.135670,-0.142508,0.188837,...,0.103974,0.054178,-0.132223,-0.206815,-0.181566,-0.330406,-0.125596,-0.115800,-0.413112,1.000000